const gameBoardTypes = {
  SET_IS_DISABLED: "SET_IS_DISABLED",
  SET_CARDS: "SET_CARDS",
  SET_FIRST_SELECTION: "SET_FIRST_SELECTION",
  SET_SECOND_SELECTION: "SET_SECOND_SELECTION",
  SET_SCORE: "SET_SCORE",
  SET_GRID_SIZE: "SET-GRID-SIZE",
  SET_MATCHED_CARDS: "SET_MATCHED_CARDS",
  START_TIMER: "START_TIMER",
  STOP_TIMER: "STOP_TIMER",
  RESET_TIMER: "RESET_TIMER",
  SET_TIMER: "SET_TIMER",
  SET_NUMBER_OF_MOVES: "SET_NUMBER_OF_MOVES",
};

module.exports = gameBoardTypes;
